### ISSUE TITLE
Is vtep port by default supposed to be 4789 or something else?

### ISSUE THREAD

**Issue by ryanpei** [cloudfoundry-incubator/cf-networking-release#12]
I noticed in the Known Issues doc I saw this warning:
When using VMware NSX for vSphere 6.x, the default VXLAN port of 8472 used by cf-networking is not allowed. To fix this issue, override the default cf_networking.vtep_port with another value.

But it looks like the default port for vtep is now actually 4789, not 8472.

Is this the same port we're referring to in the known-issues, or something else, if I'm using NSX?

**Comment by ryanpei** [comment]
cc @abbychau

**Comment by chinangela** [comment]
Hi @ryanpei,

You are correct that the default port is now 4789. Starting with NSX 6.2.3, the default VXLAN port will be 4789, so there will still be a conflict.

We will update our Known Issues doc accordingly. Thanks for pointing it out!

Cheers,
Angela and @jaydunk
