### ISSUE TITLE
cf-release docs contain wrong configuration

### ISSUE THREAD

**Issue by jhiemer** [cloudfoundry-incubator/cf-networking-release#13]
Hi,
I deployed `cf-networking-release` today with `cf-release 265` and `diego-release 1.19`. During that I found an error in the documentation. For `uaa` the configuration has the following section
```yml
authorized-grant-types: client_credentials,refresh_token
```

But if `authorized-grant-types` contains `refresh_token` you need to specify `scopes` as well in the section.

**Comment by DennisDenuto** [comment]
Hi @jhiemer,
Thanks for the feedback. 

We have updated our docs, to point to more up-to-date [supported mode of deployment instructions](https://github.com/cloudfoundry/cf-deployment).
