### ISSUE TITLE
deleting policies failed

### ISSUE THREAD

**Issue by airwing** [cloudfoundry-incubator/cf-networking-release#18]
➜  bosh-lite git:(develop) ✗ cf remove-access zuul-proxy backend --protocol tcp --port 8080

Denying traffic from zuul-proxy to backend as admin...
FAILED
deleting policies: failed to make request to policy server

api/b0c7ebc0-23c3-4f21-9119-e577af0fbaff:/var/vcap/sys/log/policy-server# tail -f policy-server.stdout.log
{"timestamp":"1500482810.026837587","source":"cfnetworking.policy-server","message":"cfnetworking.policy-server.authenticator: failed to verify token with uaa","log_level":2,"data":{"error":"bad uaa response: 400: {\"error\":\"invalid_token\",\"error_description\":\"Token has expired\"}"}}
^C

**Comment by airwing** [comment]
allow-access is OK

**Comment by jaydunk** [comment]
Is this a persistent or intermittent problem? If you `cf login` again does it fix it?

**Comment by ezhang-pivotal** [comment]
Hi Jay. cf login does not help. meanwhile allow-access does not have problem

**Comment by jaydunk** [comment]
@ezhang-pivotal Are you still seeing this issue?

**Comment by jaydunk** [comment]
@ezhang-pivotal I'm going to close this issue, feel free to open another if you run into this problem again
